version: '3.4'

services:
  wso2am:
    image: wso2/wso2am:4.1.0
    ports: 
     - 8280:8280
     - 8243:8243
     - 9443:9443
  restapi:
    image: nguyenhero/restapi
    ports: 
     - 11001:80
    build:
      context: .
      dockerfile: RESTAPI/Dockerfile
  soap:
    image: nguyenhero/soap
    ports: 
     - 11002:80
    build:
      context: .
      dockerfile: SOAP/Dockerfile
  graphql:
    image: nguyenhero/graphql
    ports: 
     - 11003:80
    build:
      context: .
      dockerfile: GraphQL/Dockerfile

